### ISSUE TITLE
Support portrait orientation

### ISSUE THREAD

**Issue by TrevorFSmith** [mozilla-mobile/webxr-ios#10]
Right now the app only runs in landscape orientation. We should set the app to work in both landscape and portrait orientation and make sure that the native UI (URL bar, recording UI, etc) works across reorientation.

**Comment by blairmacintyre** [comment]
The webview will also need to reorient (thus resize), and the data passed in may need to be adjusted to line up with the new size and orientation.

**Comment by blairmacintyre** [comment]
done.
