### ISSUE TITLE
permission dialog boxes disappear when screen is rotated

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#107]
The dialog boxes go away when the screen is rotated.  I am unsure what gets sent to the app ... yes?  no?  (haven't had time to check)

**Comment by robomex** [comment]
Which dialog boxes/alerts/popups are you noticing this on?

**Comment by blairmacintyre** [comment]
I think the world knowledge access, perhaps camera, etc.  The ones we created with the popup dialog box

**Comment by robomex** [comment]
I was able to reproduce this issue for examples that require "Video Camera Image Access" or "Access to World Sensing" by:
1. Navigating to an example that requires "Video Camera Image Access" or "Access to World Sensing"
2. Force-closing XRViewer either when the dialog box is still visible or after a selection has been made (the issue arises after a selection has been made for World Sensing pages if "This time only" or "NO" were selected – the issue does not present itself when "Always for this site" was selected)
3. Relaunching XRViewer – XRViewer will attempt to reload the last page, in this case a "Video Camera Image Access" or "Access to World Sensing" page
4. Rotating the screen with the dialog box visible presents the issue

It doesn't look like this bug results in the app acting as if a "Yes" was received in response to the prompt.

If there are simpler or different ways to replicate the issue, please let me know.
