### ISSUE TITLE
Project status & update to ArKit 2.0

### ISSUE THREAD

**Issue by Mamboleoo** [mozilla-mobile/webxr-ios#108]
Hello,
First I want to say how excited I am since I learned about this project, thanks for it!

I wanted to know what was the current status of this project and if you were working on making it work with ArKit 2.0.

Thanks!

**Comment by blairmacintyre** [comment]
The current version (in the app store, even) requires iOS 12 and uses ARKit 2.0.  We do not support all features of 2.0, but do support some.  If there is a feature you want that isn't supported, we'd also be happy to accept a PR against the develop branch (where the ongoing work takes place).

The current work is focused on converting much of it to Swift, refactoring to make things cleaner/easier to use in other projects, and (soon) converting to the release version of WebXR.
