### ISSUE TITLE
ARKit doesn't initialize when front-facing camera is active during page's initial load

### ISSUE THREAD

**Issue by robomex** [mozilla-mobile/webxr-ios#109]
When loading a face-tracking example like "World Sensing" or "Face Tracking" – if the front-facing camera is the active camera upon initial load, ARKit will not be initialized.  

Currently, in order to load a face-based AR experience the rear-facing camera needs to be active when the page is navigated to (or reloaded) and then after ARKit initializes the camera can be switched to the front-facing camera.

**Comment by blairmacintyre** [comment]
This is likely caused by some internal optimizations.  When a face anchor is updated, only the geometry is passed into the web page.  But, if a face is visible before the webxr session starts, the app is already processing "anchorUpdates" from ARKit, so the first message about the face is lost.

**Comment by robomex** [comment]
A quick solution to this issue, which may warrant future changes, was implemented with: https://github.com/mozilla-mobile/webxr-ios/commit/ea624af6628e179fa7ca15f841b0fd89aa0e5a2b

**Comment by blairmacintyre** [comment]
I think your solution is the correct one.

**Comment by robomex** [comment]
Update to this issue addressed in [this](https://github.com/mozilla-mobile/webxr-ios/commit/5fc179f53a54817864b89209f4d5acb69d6533be) commit, but this is still not completely fixed:
Before app sends the complete face, there are two entries in “newObjects” which are for the same face, with just the old data.

**Comment by blairmacintyre** [comment]
Probably need to do a pass over the list of objects when you delete the face anchor to make sure it's been cleared out.
