### ISSUE TITLE
Only head-model hit testing is supported

### ISSUE THREAD

**Issue by Fehler40** [mozilla-mobile/webxr-ios#116]
Hey,
I'm trying to implement hit-testing in my webXR app. In the onSessionStarted function I set the frame of reference, but I'm forced to do this in 'head-model'. When I try to set it to 'eye-level' I get this error:` Unhandled Promise Rejection: Only head-model hit testing is supported`

This is the onSessionStarded-function: 

```
onSessionStarted = async () => {
    this.setState({ isARSessionStarted: true, arMessage: 'session started' });
    this.renderer = new THREE.WebGLRenderer({
        alpha: true,
        preserveDrawingBuffer: true,
    });
    this.scene = new THREE.Scene();

    this.renderer.autoClear = false;
    this.renderer.shadowMap.enabled = true;
    this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
this.gl = this.renderer.getContext();

await this.gl.setCompatibleXRDevice(this.session.device);
this.session.baseLayer = new window.XRWebGLLayer(this.session, this.gl);

const framebuffer = this.session.baseLayer.framebuffer;
this.renderer.setFramebuffer(framebuffer);       

 // this.camera.matrixAutoUpdate = false;
//  this.camera.position.z = 100;
this.camera = new THREE.PerspectiveCamera();


this.frameOfRef = await this.session.requestFrameOfReference('head-model');
this.session.requestAnimationFrame(this.onXRFrame);

};

```
And my Hit-Test function:
```
onTouchStart = async () => {
        //navigator.vibrate(200);
        const geometry = new THREE.BoxGeometry(20, 20, 20);
        const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
        // geometry.applyMatrix(new THREE.Matrix4().makeTranslation(0, 0.25, 0));
        this.model = new THREE.Mesh(geometry, material);
       
    
        let x = 0;
        let y = 0;

       
        this.raycaster.setFromCamera({ x, y }, this.camera);
        const ray = this.raycaster.ray;

        const origin = new Float32Array(ray.origin.toArray());
        const direction = new Float32Array(ray.direction.toArray());

        //returns a promise which stores matrices of the location of the hit 
        
        const hits = await this.session.requestHitTest(origin, direction, this.frameOfRef);

        //https://github.com/immersive-web/webxr/blob/master/hit-testing-explainer.md
        
     
        if (hits.length) {
            this.setState({ arMessage: 'hits' });
            const hit = hits[0];

              const hitMatrix = new THREE.Matrix4().fromArray(hit.hitMatrix);

            this.model.position.setFromMatrixPosition(hitMatrix);
            this.scene.add(this.model)

        } else {
            this.setState({ arMessage: 'no hits' });
        }
    };
```

So the behavior of my app is strange. When I want to add an object on the surface, it instead "sticks on the display" and moves with the camera. Is this caused by 'head-model'? Is there a way to fix this? Or is this why I don't use the mozilla/webxr-polyfill? Sorry, I'm a newcomer and slightly confused. I am on iOS in the XRViewer Browser.

Thanks!

**Comment by blairmacintyre** [comment]
What polyfill are you using?  None of the samples for the WebXR Viewer's old polyfill (github.com/mozilla/webxr-polyfill) have an `onSessionStarted` and that old polyfill doesn't have `session.requestAnimationFrame`.

Or are you not including a polyfill?

**Comment by Fehler40** [comment]
Thank you for responding. I am not including any polyfill. So I'm wondering why it knows the `session.requestAnimationFrame`. If I want to do it proper like in the samples, I have to use the github.com/mozilla/webxr-polyfill, isn't it? 
Can I use this polyfill (mozilla/webxr-polyfill) also on Android (in the google-ar/WebARonARCore)?

**Comment by blairmacintyre** [comment]
Ok, that makes sense.

If you look in github.com/mozilla-mobile/webxr-ios-js, you will see the beginnings of a modification to the official immersive-web/webxr-polyfill that works with our app.  We are embedding that in the app -- the long term goal is to have the WebXR Viewer walk and talk and behave as if it has WebXR natively implemented.  The immersive-web/webxr-polyfill hasn't been updated in a bit, as the spec proposal continues to evolve, and we plan on adding more of the WebXR Viewer features to this version of the polyfill soon.

I am unsure if our mozilla/webxr-polyfill still works on WebARonARCore (it did at one point, and it may still, but I haven't tested it in ages).

Note that the mozilla/webxr-polyfill is based on an old proposal for WebXR that we did, and is not exactly the same as the evolving standard.  The differences are small, but important (in that, pages written for one won't work in the other).

Once the spec stabilizes and we finish webxr-ios-js, the mozilla/webxr-polyfill will be completely deprecated.

**Comment by blairmacintyre** [comment]
All of this is in flux, so it's kind of a mess right now! 😱

**Comment by Fehler40** [comment]
Thanks for all the informations! I think I missed that to understand it finally. 
So I am planning to develop an webbased AR-App for iOS and Android (with one code-base in the best case). The features I need are hittesting and maybe world sensing. Do you have an advice for me, which polyfill I should use in the moment? I think it will be the mozilla polyfill but I should test it on Android first. 
Last question to make it clear: Is mozilla's XRViewer the only way right now to have the webxr experience on iOS? 
Thank you!

**Comment by blairmacintyre** [comment]
Have you looked at Chrome Canary on Android?  I know it's a bit unsupported, but it's likely more supported than the WebARonARCore.  It might (?) support hit testing?  I'm not sure.

The mozilla-mobile/webxr-ios-js (the extension for WebXRViewer to the official webxr polyfill) supports hittesting, so it might suffice for what you need?   You can at least look at the code to both (github.com/immersive-web/webxr-polyfill and github.com/mozilla-mobile/webxr-ios-js) to see how the polyfill and our extension works.

_IF_ Chrome Canary on Android supports hit testing, _AND_ the syntax is similar to webxr-ios-js, then that might be the easiest and most future-proof route.   OR, if the mozilla/webxr-polyfill works on WebXROnARCore, that may also be a reasonable short-term route.

As for iOS, yes, as far as I know, this is the only browser that supports WebXR.

**Comment by vincentfretin** [comment]
On my project, WebAROnARCore still works with latest mozilla webxr-polyfill on Android 9 on my S8. But be aware WebAROnARCore works only with the old ARCore-preview.apk (so only S8 and Pixel at the time of this apk release, and still called Tango Core in Applications). It doesn't use the latest ARCore from Google Play (ARCore in Applications).

**Comment by Fehler40** [comment]
Okay, thank you. I will take care of this!
I will start developing and come back here if I have trouble with something. Hope you will be still here :) 
I will close this for now. Thank you!
