### ISSUE TITLE
The messagePanel that displays tracking status updates sometimes displays an empty box

### ISSUE THREAD

**Issue by robomex** [mozilla-mobile/webxr-ios#127]
I believe this happens in between message transitions.  

Should either get rid of that momentary display or display a useful message instead of an empty box.

**Comment by blairmacintyre** [comment]
Also, we should consider moving this, and making it a bit more legible;  all corners of display are likely to have "UI" in them.

Perhaps consider doing it two ways:  
- when URL bar is hidden, put an icon in the upper right corner, perhaps color coded orange and red (red for things that cause "no tracking").   
- when URL bar is shown, get rid of the icon (it would be behind URL bar) and put this text back, but make it less transparent
