### ISSUE TITLE
first WebXR session takes a while to respond

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#135]
If you have the debugger open, you'll see a timer invalidation and then a restart;  not sure why this causes a big delay, perhaps a time being checked wasn't initialized?

**Comment by robomex** [comment]
That timer is for tracking time and pausing the ARSession after a set period (default: 60 seconds) of being on a non-XR site.  
Previously, every time an ARRequest was sent an "Invalidate Timer" message was printed even if the timer was nil & no invalidation was taking place.
This commit makes a change to only print "Invalidate Timer" when a timer is actually being invalidated: https://github.com/mozilla-mobile/webxr-ios/commit/f7e7074eb17bd6ea60c9bf5ca0944323271cd6fa 

However the root issue (First WebXR session takes a while to respond) still remains – I haven't noticed big delays, is there a device/example/process that reliably produces the delay?

**Comment by blairmacintyre** [comment]
It's worse when you run for the first time after install;  or the first time after killing it.  On my iPhoneXS and SE, it's 3 or 4 seconds between hitting "GO" on a demo and getting the permissions popup

**Comment by robomex** [comment]
Discussion continued in the original submission, here: https://github.com/mozilla-mobile/webxr-ios/issues/129
