### ISSUE TITLE
Revisit AppState start/run/resumeSession methods

### ISSUE THREAD

**Issue by robomex** [mozilla-mobile/webxr-ios#136]
updateARConfiguration should account for/handle numberOfTrackedImages.
switchCameraButtonTapped should (?) call runSession(with state) rather than run.session.

**Comment by blairmacintyre** [comment]
I think commit https://github.com/mozilla-mobile/webxr-ios/commit/33910f9a1302eb8a36c9030eea315a20dbd4782a fixes this.
