### ISSUE TITLE
run a page with image targets, the next page I ran detected one

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#143]
I think that when we end a session and keep ARKit going for a little while while on a non-XR page (or just when we reload), we aren't clearing out the `worldTrackingConfiguration?.detectionImages`

**Comment by robomex** [comment]
This issue was addressed in 1.13 with this commit: https://github.com/mozilla-mobile/webxr-ios/commit/2442acfc3a871b5f8109e0fee1443aaa8b36d2a3
Closing this issue.  If a related bug appears, please submit a new issue with relevant information.
