### ISSUE TITLE
anchors (and their dictionaries) need to be rebuilt after "initAR"

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#144]
InitAR is where the `geometryArrays` property is set, controlling the format of the dictionary.

Initially it defaults to `false`, so any anchor detected before `initAR` will be in the old format.  After an app is run, the anchors will eventually get updated to the right format, and new ones will have the right format.

If another app is then run, and it uses a different value for `geometryArrays`, all the existing internal anchors will, again, be in the wrong format.

The right solution to this is to add something like a function `blockSelf?.arkController?.recreateAllAnchorDictionaries()` and call it at the end of `onInitAR` in ViewController.

Similarly, at that same place, we can remove any ImageAnchors we encounter (they would be left over from the previous run) and make sure the ARKit Controller does not have any active tracking targets (problem reported in #143 )

**Comment by robomex** [comment]
This issue was addressed in 1.13 with this commit: https://github.com/mozilla-mobile/webxr-ios/commit/4a8f08482ad1368befff75755b2847b6ed6b4015
Closing this issue.
