### ISSUE TITLE
consider making the URL bar less transparent

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#145]
When in XR, and the menu is slid down, make it "mostly opaque" instead of "mostly transparent".

Usual operation will have the menu hidden;  but when it's down, it should be much more visible and clear, with just a hint of the AR content showing through.

**Comment by robomex** [comment]
Agreed!  In certain lighting/environments the debug button was difficult to make out.  It's more legible with the decreased transparency.
