### ISSUE TITLE
make use of ARKit in the app more robust over time 

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#158]
There are three issues related to this, #133 #132 #126.  

I think we can go along way to dealing with these if we do the following:
- add a new setting "max ARKit run time", default it to something like 15 minutes.  It is the length of time that ARKit can be running before we completely reset it (equivalent to the reset menu) on the next "request session"

- any time we request a session, we get rid of any attempts at relocalization

**Comment by robomex** [comment]
These issues were addressed and included in the last release.
