### ISSUE TITLE
history gone after webview crash

### ISSUE THREAD

**Issue by joshmarinacci** [mozilla-mobile/webxr-ios#18]
I think i found a bug. The first time I loaded the simple example it the webview crashed with an out of memory error.  then it reloaded the page but the history was gone so I couldn’t get back to the main page listing all of the examples

**Comment by blairmacintyre** [comment]
It should always start on the main page right now.  We don't save history.  It would be nice if it always re-opened the last page, remembered (some amount of) history, and had a home button.

Similar to #20

**Comment by robomex** [comment]
URL that caused an error is preserved by [commit 702f95b3e4089fae2666d45076fd1b67eb337fc0](https://github.com/mozilla-mobile/webxr-ios/commit/702f95b3e4089fae2666d45076fd1b67eb337fc0).
Home button added by [commit 20cc419f22114f92e9d77dbf384ff6ab9cd209c5](https://github.com/mozilla-mobile/webxr-ios/commit/20cc419f22114f92e9d77dbf384ff6ab9cd209c5)

**Comment by blairmacintyre** [comment]
At some point soon we should start shipping test-flight builds and releasing new versions.

Is the current develop stable?

**Comment by robomex** [comment]
Yes – the current develop branch is stable.

My naive testing process primarily consists of quickly running through all the Samples & Simple Examples to confirm they work (with the exception of "A-painter fox" and "A-painter Balrog," I noticed even when using a build from before I started working on the code that these two have a stuttering issue when placing the pin).

The most obvious blind spots of this testing process is potential errors/bugs/crashes that may result either from prolonged use of a particular example/functionality or repeated use of a particular example/functionality within the same session.

**Comment by blairmacintyre** [comment]
Ok, I'll publish a build.

Perhaps we should start thinking about ways to have test cases.  Hmmm.

**Comment by robomex** [comment]
Agreed on test cases.  

The time manual testing eats up quickly explodes as more AR interactions are added and older ARKit-capable devices are added to the testing stable.

It appears like there's still a significant void when it comes to automated ARKit-testing, but I'm sure we can come up with something.
