### ISSUE TITLE
Isn't this app banned by Apple App Store Guildines 4.7?

### ISSUE THREAD

**Issue by greggman** [mozilla-mobile/webxr-ios#184]
From the [guidelines](https://developer.apple.com/app-store/review/guidelines/#third-party-software)

> 4.7 HTML5 Games, Bots, etc.
>
> Apps may contain or run code that is not embedded in the binary (e.g. HTML5-based games, bots, etc.), as long as code distribution isn’t the main purpose of the app, the code is not offered in a store or store-like interface, and provided that the software (1) is free or purchased using in-app purchase; **(2) only uses capabilities available in a standard WebKit view (e.g. it must open and run natively in Safari without modifications or additional software); your app must use WebKit and JavaScript Core to run third-party software and should not attempt to extend or expose native platform APIs to third-party software;** (3) is offered by developers that have joined the Apple Developer Program and signed the Apple Developer Program License Agreement; (4) does not provide access to real money gaming, lotteries, or charitable donations; (5) adheres to the terms of these App Review Guidelines (e.g. does not include objectionable content); and (6) does not offer digital goods or services for sale. Upon request, you must provide an index of software and metadata available in your app. It must include Apple Developer Program Team IDs for the providers of the software along with a URL which App Review can use to confirm that the software complies with the requirements above.

So, providing a polyfill for WebXR sounds like it's prohibitied? Basically if the pages don't run in native safari they aren't allowed to run in this app either.

**Comment by blairmacintyre** [comment]
Hi @greggman.  Unfortunately, we do not comment on legal issues in github repos.
