### ISSUE TITLE
basic URL completion

### ISSUE THREAD

**Issue by joshmarinacci** [mozilla-mobile/webxr-ios#19]
If you type in a url without the http part you can't load it.  ex:  vr.josh.earth does not expand to http://vr.josh.earth/

**Comment by blairmacintyre** [comment]
In general, the URL handling is terrible and needs to be dramatically improved.  Numbers don't work, either.

**Comment by blairmacintyre** [comment]
done in demo version.  Need to publish.

**Comment by robomex** [comment]
Resolved in [commit 82f65c130eb506e4261a8e4174c2baf796cb36b3](https://github.com/mozilla-mobile/webxr-ios/commit/82f65c130eb506e4261a8e4174c2baf796cb36b3).
