### ISSUE TITLE
Maybe add a home button?

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla-mobile/webxr-ios#20]
Andre had loaded an older version of the app that had the original exalt URL and it defaulted to that even after reinstall of the app. Maybe have a home button to go to the default screen? Or don't save the current URL across reinstalls?

**Comment by blairmacintyre** [comment]
Good idea.  Would also like the ability to remember the last used URL so you don't have to always re-enter it.

**Comment by blairmacintyre** [comment]
Done in develop version.  Need to publish

**Comment by blairmacintyre** [comment]
works.
