### ISSUE TITLE
when URL bar is shown, bottom of webview is offscreen

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#25]
Looking at the XCode inspector of the app, the WKWebview is shifted down (as expected) but it's height is still the height of the screen:

`<WKWebView: 0x13a818e00; frame = (0 49; 667 375); opaque = NO; autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x1c403bd80>>
`

When the URL is shown, the webview should shrink in height, otherwise the bottom of the web contents are hidden.

Any non-AR page exhibits this behavior.

**Comment by blairmacintyre** [comment]
This will require adjusting the size of the webview, which may break some web code, so I'm marking this as less urgent for now.

**Comment by che1404** [comment]
I've pushed a fix that basically applies an inset from the top part of the webview, instead of applying an offset to the y coordinate of the webview position. It basically shrinks the webiew, instead of moving it.
Testing would be appreciated!

**Comment by blairmacintyre** [comment]
Doesn't work, as I feared.  The polyfill and other apps don't respond to webview resizes properly.  Can you disable this code with a FLAG, and then we can reenable and test when we have time to fix the polyfill and apps?

**Comment by che1404** [comment]
Sure!

**Comment by che1404** [comment]
@blairmacintyre I suppose this is fixed now thanks to your changes in the polyfill and my changes on the iOS app?

**Comment by blairmacintyre** [comment]
done.
