### ISSUE TITLE
warning indicator is not useful

### ISSUE THREAD

**Issue by joshmarinacci** [mozilla-mobile/webxr-ios#26]
When ARKit has not detected the floor it shows a warning indicator, but this doesn't really tell the user what's going on, or what to do about it (namely that they should move around).

**Comment by blairmacintyre** [comment]
There are a few different states ARKit can be in, most of them just show this "warning" indicator.
WEB_AR_TRACKING_STATE_LIMITED: 
WEB_AR_TRACKING_STATE_LIMITED_INITIALIZING:
WEB_AR_TRACKING_STATE_LIMITED_FEATURES: 
WEB_AR_TRACKING_STATE_LIMITED_MOTION: 

One more (WEB_AR_TRACKING_STATE_NOT_AVAILABLE) shows a Error indicator.   WEB_AR_TRACKING_STATE_NORMAL shows nothing, but may still not have found planes.

We could easily use different feedback for each:  each of them is just an image, in 3 resolutions (e.g., Warning is 78x19, 156x38, 324x57).  I think it would be trivial to use different images/icons for each of these conditions (or just a different one for all that says more than "Warning" and "Error").  

Care to make something that makes more sense to you?  I can try dumping them in.

**Comment by blairmacintyre** [comment]
Need:  
- ARKit not initialized yet, look around
- Moving too fast
- Not enough visual features
- No planes detected yet

**Comment by joshmarinacci** [comment]
Since we are likely to change the text and add messages over time, let's use a text indicator instead. Can you put black text on a translucent white/gray background like this:

https://docs-assets.developer.apple.com/published/f385e426f2/d665844f-2945-44f9-9896-06a1bb53251a.png

**Comment by blairmacintyre** [comment]
Let's let @che1404 decide what's easiest:  going to text means we can't have icons.  I'd like to get something out quickly so people can comment, and we will probably want a combo of text and graphics eventually, right?

**Comment by joshmarinacci** [comment]
Don’t Cocoa labels have text + an icon?

**Comment by blairmacintyre** [comment]
Dunno. :)

**Comment by che1404** [comment]
Hey. UILabels don’t have text + icon AFAIK. But we can add a simple custom UIView containing both a text and an image. 
How does it sound?

**Comment by blairmacintyre** [comment]
If it's simple, sure.  An icon on the left, text on the right?  Then we can just do the color/shadow/outline/etc on the text with iOS text styling?  And have nice high-res text on all platforms?

**Comment by che1404** [comment]
I’ll have a look at the text styling possibilities. I’m not sure about the outline, but the colors and the shadows should be supported.

**Comment by blairmacintyre** [comment]
ok.  Don't do anything that will take a ton of time;  we just want to get something out first, so people can try it and see if it helps.

**Comment by che1404** [comment]
Ok. Then I’d suggest to go for the “just” images approach and then create another issue for a custom view.

**Comment by che1404** [comment]
(And maybe implement it in the future?)

**Comment by blairmacintyre** [comment]
That would be my preference.

**Comment by joshmarinacci** [comment]
![messages](https://user-images.githubusercontent.com/276938/33338207-2884bcc2-d42a-11e7-85d1-5b185846de15.png)

What do you think of this? It's rendered at 2x resolution. Need more bg blur?

**Comment by blairmacintyre** [comment]
check out the current version of the app;  he's added new labels.

**Comment by joshmarinacci** [comment]
ah. much better

**Comment by blairmacintyre** [comment]
done
