### ISSUE TITLE
add iPhoneX support

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#30]

**Comment by che1404** [comment]
@blairmacintyre I'm wondering if we should take the chance and add autolayout code to fix this issue, and stop using hardcoded view/frame sizes.
Thoughts?

**Comment by blairmacintyre** [comment]
Whatever is easiest.... if they autolayout is doable, and doesn't break, it seems wise:  I assume you could use the same autolayout code to adjust the icon sizes?

**Comment by che1404** [comment]
Yes, you're right.

**Comment by blairmacintyre** [comment]
done.
