### ISSUE TITLE
Analytics integration

### ISSUE THREAD

**Issue by che1404** [mozilla-mobile/webxr-ios#35]
Hi all,
looking at the native part of the app, I cannot see any analytics event tracking, so we cannot know how many users will be using the app, or how are they using it.

We have plenty of analytics alternatives out there. Google Analytics for Firebase is the one I usually recommend for iOS, mainly because it's mobile-oriented: it provides with the common mobile app events, like first time usages, or uninstalls, out of the box.

Of course, since we are using GA on the web side, it may be also interesting to have the GA iOS SDK instead of the one provided by Firebase. This way, we will have all the analytics stuff in the same dashboard.

Thoughts?

**Comment by blairmacintyre** [comment]
Thanks, yes, I agree.  We're using buddybuild to build the app, so we can probably get some of this from them.  And we have GA set up for the web code, so adding in their SDK would be easiest.

**Comment by blairmacintyre** [comment]
We are going to use Mozilla's service, add a settings menu to the app, and a Privacy Notice.
