### ISSUE TITLE
Cookies are not retained across app restart

### ISSUE THREAD

**Issue by TrevorFSmith** [mozilla-mobile/webxr-ios#36]
What happens:
Create a web page that sets a cookie with a timeout in the future.
Restart the app.
The cookie is no longer there.

What I expect to happen:
The cookie is retained across app restarts.

**Comment by che1404** [comment]
I'd suggest having a look at [WKWebsiteDataStore](https://developer.apple.com/documentation/webkit/wkwebsitedatastore?changes=latest_minor). It seems that a new property "httpCookieStore" of type [WKHTTPCookieStore](https://developer.apple.com/documentation/webkit/wkhttpcookiestore?changes=latest_minor) arrived with iOS 11.

**Comment by blairmacintyre** [comment]
@trevorfsmith I’m not sure this is true.  I just tested cookies by visiting   http://www.whatarecookies.com/cookietest.asp

Refreshing a few times ups the count of visits. If I kill the app and restart, it shows the same count (i.e., the cookie is still there).

Is there something particular about the cookie trying to use?  Or are you doing something different, not using cookies?

**Comment by blairmacintyre** [comment]
Looks like this is fixed.
