### ISSUE TITLE
Integrate code in "exalt" branch

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#38]
The last code submission done by the exalt team is in the exalt branch.

We need to integrate the code, and make sure the polyfill is updated at the same time.

This code should
- allow app to be rotated
- send all ARKit info into app (plane data, auto-found anchors)
- notify apps when anchors are lost
- efficiently upload anchor data to webview

**Comment by blairmacintyre** [comment]
See https://github.com/mozilla/webxr-polyfill/issues/57

**Comment by blairmacintyre** [comment]
I think most of this has been done, without their code.

**Comment by robomex** [comment]
Doing some cleanup & closing this issue.  

If this should remain open please add a note on what's still to be done.
