### ISSUE TITLE
Ability to change the default URL via app settings

### ISSUE THREAD

**Issue by che1404** [mozilla-mobile/webxr-ios#39]
We want to let the user change the default URL in the app settings.

**Comment by che1404** [comment]
So I have implemented this as follows:
- On app launch, always open the last visited URL, if it exists.
- If it's not set yet, open what the user has in app settings as Home URL.
- From now on, the app will always open the last visited URL. 
- Also, when the user taps on home button, we will redirect him to the Home URL he put in settings.

Makes sense?

**Comment by blairmacintyre** [comment]
Makes sense to me.  I've pushed this to testflight, so folks can test.  But it seems to work for me.

**Comment by blairmacintyre** [comment]
seems to work.
