### ISSUE TITLE
Make sure ARKit is initialized to align with GeoSpatial reference frame (EUS)

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#41]
When initializing ARKit, you can ask to align the coordinate system such that X is east and Z is south.  We should do this.

Eventually, we want to make this an initialization option from javascript, but until then, the app should always do this.

**Comment by blairmacintyre** [comment]
Set the worldAlignment property on the ARConfiguration before init 

https://developer.apple.com/documentation/arkit/arconfiguration/2923550-worldalignment?language=objc

to ARWorldAlignmentGravityAndHeading

https://developer.apple.com/documentation/arkit/arworldalignment/arworldalignmentgravityandheading?language=objc

**Comment by blairmacintyre** [comment]
in ARKController, initWithType method

**Comment by che1404** [comment]
Tested with a compass:

- Z, South (Red)
- X, East (Blue)
- Y, Gravity Up (Green)

Works as expected. From the docs: 

> The x- and z-axes match the longitude and latitude directions as measured by Location Services. The vector (0,0,-1) points to true north and the vector (-1,0,0) points west. (That is, the positive x-, y-, and z-axes point east, up, and south, respectively.)

![eus](https://user-images.githubusercontent.com/290546/33701527-6a1d5b70-db1f-11e7-966e-b64930a79f3c.JPG)

**Comment by blairmacintyre** [comment]
I tested it too, seems to work correctly.
