### ISSUE TITLE
launch URL doesn't always work

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#43]
Sometimes I click the launch URL, and the app opens, but doesn't go to the URL -- not sure the conditions, wondering if it's overriding the launch URL and going to the "last saved" URL?

**Comment by che1404** [comment]
I just pushed a fix to that. You were right: when the app was completely closed, we weren't looking for the requested URL. Now we do.
Testing would be appreciated!

**Comment by blairmacintyre** [comment]
Seems to work.
