### ISSUE TITLE
add preference control to toggle Google Analytics collection on/off

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#44]
We would like to give people the option to opt-out of GA analytics collection, even though the amount of data is small.

So, we should add a boolean to the preferences that toggle collection on/off.

It should default to "on".

Perhaps say "Allow app usage data collection"?

**Comment by che1404** [comment]
Done, and pushed. 
Testing appreciated!

**Comment by blairmacintyre** [comment]
done.
