### ISSUE TITLE
When AR Session fails to initialize, provide more feedback to web apps

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#47]
Here, we need to ensure more error/failure info is sent to javascript.  over in the https://github.com/mozilla/webxr-polyfill we'll need to make sure to display it.

**Comment by che1404** [comment]
Currently on ARSession failure we just show a popup with the error message, and when the user taps on "OK", the webview reloads.

Do we have any proposal on the message to send to the polyfil when we get an error?

Following the same pattern as other messages, we could add other one like:
"arkitDidFail", sending the ARKit errorCode and a message.

Thoughts?

**Comment by blairmacintyre** [comment]
Two things: 
- when there is an ARSession failure, I'd still prefer the web page NOT To auto-reload:  the user should have the URL in the URL bar, and can hit reload if they want.  Same for out of memory errors;  perhaps kill the page and re-open an empty page, perhaps with the URL pre-loaded in the bar?  Is that possible?
- for these errors, I'm happy to ignore this suggestion here;  I don't think we need to send error messages over yet, or we could send over as much info as you can (in whatever format is reasonable) to a new method ... not sure what to do with the message, though.

**Comment by che1404** [comment]
> when there is an ARSession failure, I'd still prefer the web page NOT To auto-reload: the user should have the URL in the URL bar, and can hit reload if they want. Same for out of memory errors; perhaps kill the page and re-open an empty page, perhaps with the URL pre-loaded in the bar? Is that possible?

Yes, that's possible. So we keep the same popup, but the OK button launches the empty page and shows the URL in the bar.

> for these errors, I'm happy to ignore this suggestion here; I don't think we need to send error messages over yet, or we could send over as much info as you can (in whatever format is reasonable) to a new method ... not sure what to do with the message, though.

I think that depends on how the polyfill will handle the error information. Maybe Arturo can shed some light on this one?

**Comment by blairmacintyre** [comment]
Ok, do the change for the ARSession Failure;  would also like that to be the behavior for the out-of-memory error and similar things -- auto-reload seems like a bad idea, just causes loops.

As for how the polyfill will handle it;  I think if you're just calling an error method, we can route however we want.  We just need to have the method there to receive.  Could probably write the method first.  Arturo is out for a few days.
