### ISSUE TITLE
Add communication between webView and iOS to remove all extra UI of the app

### ISSUE THREAD

**Issue by arturitu** [mozilla-mobile/webxr-ios#48]
I think this could be the best way to remove all the UI of the native app.
For example to capture video/audio, show/hide ARKit info… which now are called from native buttons, or to show or not warning messages, I think to have documented some specific calls from javascript code to iOS to make all these things, should be the best way to have a clean webView to add the UI needed from the client side (every webpage made to be used with the viewer can use them). Related with this, to have curated examples with recommended icons should be a good practise to have something to other developer can start ti use it.

**Comment by blairmacintyre** [comment]
We re-did the UI to use swipes to show/hide URL and camera UI elements.  So, I think this isn't needed now.
