### ISSUE TITLE
webXR viewer doesn't work when location services are disabled

### ISSUE THREAD

**Issue by frederic-schwarz** [mozilla-mobile/webxr-ios#50]
opening any of the examples from
http://ios-viewer.webxrexperiments.com/
with an iPhone SE iOS 11.2.1
shortly displays the camera feed followed by a popup saying:
```
AR Session Failed
Tab 'Ok' to restart the session
```
pressing Ok will reopen the popup
navigating away is not possible

**Comment by blairmacintyre** [comment]
This error means it can't initialize ARKit.  Some folks who've seen this had inadvertently not given permission to all the perm prompts the app asked for.  There has been one person who had this problem that we couldn't figure out.  But I'm pretty sure the SE supports ARKit.

**Comment by frederic-schwarz** [comment]
right, I found out that the reason for the app not working was that location services where disabled on the phone

**Comment by blairmacintyre** [comment]
Glad you found it!  We'll add more descriptive error messages.
