### ISSUE TITLE
sometimes the app content in the samples isn't picking up the initial orientation of the phone 

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#52]
if I start in landscape, the "hit test" example has the initial cube moving with the wrong orientation (rotate up/down, the cube moves left/right). 

I suspect the example isn't getting the initial orientation of the phone, and assumes landscape. 

Rotating the phone fixes it.

I don't know if this is an app problem (are we sending the right initial orientation?) or webxr-polyfill (are we using the right initial orientation?).

**Comment by che1404** [comment]
@blairmacintyre strange... I tried a few times launching in landscape (both right and left), and cannot reproduce it on iPhone X.

**Comment by blairmacintyre** [comment]
I'll try on my X in a minute;  just played with it and if I'm in portrait, and hold the phone flat facing down, and launch a webxr website (the anchors demo), I get this behavior.

**Comment by che1404** [comment]
Ah, sorry, I thought you meant the problem appeared on landscape, not portrait. I'll keep trying.

**Comment by che1404** [comment]
You're right. I can see it now. Working on it!

**Comment by che1404** [comment]
I just pushed a fix. Testing appreciated!

**Comment by blairmacintyre** [comment]
fixed, I think.
