### ISSUE TITLE
Is it possible to leave ARKit active between pages?

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#53]
The need to reinitialize ARKit each time we go to a page is frustrating.

Would it be possible to leave it running?  We could
- not render the camera when it's not an AR page.
- would it be possible to be more efficient and "suspend" ARKit in some way that doesn't lose state?
- perhaps if we're worried about power we could shut it down if a certain amount of time has passed when it's not on an AR page.  That way page->page navigation works, or other kinds of things like browsing a non-AR page.  Even a few minutes might be worth it, but longer might be ok.  Probably not worth it.
- delete all the page-created anchors between pages, but keep the planes and other "system created" anchors, so the main state stays (especially the planes)

**Comment by Jordan-Campbell** [comment]
This is a function of ARKit itself - it only tracks when the ARSCNViewController is active, i.e. when the session is running. 

You can save the relative transformation between nodes, but not the transformation from any nodes back to the origin, as the origin is lost when tracking is paused. Apple will add support for this (and there are a few third party libraries) but it won't be until 2019/2020 ish.

**Comment by blairmacintyre** [comment]
I've asked @che1404 about this, since it's so frustrating to have to completely reinitialize ARKit on each page.  Essentially, I asked him for exactly the same things, with the same suggestions you have (timeout to shutdown, delete page-created anchors, and so forth).  We're looking at it, there have just been other things higher priority (and, we've been looking at iOS 11.3 beta and ARKit 1.5).  

(If there are any iOS devs watching, a PR for something like this (on the develop branch, of course), would be whole wholeheartedly welcomed.)

**Comment by blairmacintyre** [comment]
Additional question:  since we have a random string id for each anchor, we should think about implementing some kind of same-domain policy to control when anchors are destroyed.  Specifically, if an AR page is the same domain as the previous AR page, we should not destroy the anchors that page created.  

We can pass them in, with their ID's, and if they app knows what to look for (i.e., a multi-page app saved and shared the id's of anchors, perhaps in a cookie or some app-specific mechanism) it can find anchors created by the previous page.

Need to talk to the security folks about this, tho.

**Comment by che1404** [comment]
@blairmacintyre I think we could just use the ARKit ARSession API to "pause" the session. That way, we wouldn't get any updates until we call "run" again, and we'll keep all the anchors.

More on this: https://developer.apple.com/documentation/arkit/arsession/2865619-pause

**Comment by blairmacintyre** [comment]
I guess the question is, will pausing it for a long time cause ARKit to lose track of where it is, etc.  Does it really stop tracking?  

If pausing causes it to get lost and need to be initialized, that might not be as useful.  HOWEVER, if pausing works for a short time (a minute or so) or works as long as you don't move too far, that would be fine.

**Comment by che1404** [comment]
@blairmacintyre I will do quick demo to test this and will post here the results.

**Comment by blairmacintyre** [comment]
done
