### ISSUE TITLE
Expose "image tracker" in a platform independent way via webxr-polyfill

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#60]
A possible way to expose image tracking is as follows:
- create a `XRTracker` object representing a generic tracking service.  Here it's images, but could have a QRCode one, or ARToolkit, or in Argon the various Vuforia trackers
- add `session.getTracker("name");` method to find a tracker by name.  This one would be "image"
- `XRImageTracker it` is a tracker service for finding and tracking images in 3D.  It would have a `ri = it.createReferenceImage(img, realWorldWidth, realWorldHeight)` to create a image from a buffer;  returns a promise to let this be async; `it.addImage(ri)` to start searching for that image; `it.removeImage(ri)` to stop searching
- when an trackable (image in this case) is found, a new XRImageAnchor is created, which is an XRAnchor specific for this image.  
- Need some sort of listener for new anchors 
- add `isTrackable` property to XRAnchor to denote if the anchor can be tracked when it moves (versus just found an have a pose for it's initial position/orientation).  In ARKit, image aren't trackable, but faces are.  In ARToolkit/Vuforia, images are trackable.
- add `isTracked` property to XRAnchor to denote if it's currently being actively tracked, or if the pose is "last known position"
- also need a way to destroy anchors from javascript (if it's not there)

Putting this here because the app needs to expose functions to make this possible.

**Comment by Thaina** [comment]
Is this already possible?
