### ISSUE TITLE
Need a single page to be able to go in/out of AR 

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#63]
When I visit a normal web page, I get an opaque URL bar at the top, and the browser behaves like a normal page.

When the page initializes a WebXR session, it switches to full-screen AR.  Which is great.

But, I should be able to shut the session down and have the page return to normal, as it was when I started.  Or, at least, switch the background back to opaque white so it appears as a normal page.  

Then I should be able to go into AR again, and out of it, and so on.  As much as I want.

**Comment by che1404** [comment]
This should be already working on the work in progress branch **origin/wip_initAR_watchAR_stopAR**
If you try http://xr-store.webxrexperiments.com/ you can switch from AR to 2D and back again as many times as you need.
Please let me know if that's the expected behavior.

**Comment by che1404** [comment]
Also, another thing that we wanted to have was the ability for the viewer to start the tracker on initAR, without waiting for a watchAR message. I've been analyzing this in code, and doing some tests, and here's what's happening (Using http://blairmacintyre.github.io/hri-ar-workshop-2018/):
1. Reload page
2. Web side sends initAR to the app
3. App responds with initAR and waits for the respose, but **before we get a response:**
4. Web side sends watchAR, so the app handles onWatchAR and **starts the AR session**
5. Finally, the app handles te initAR response, and calls onInitAR, but the **session already started** on the last watchAR

So, if we want to implement this feature, I think that we need the polyfill to decouple the initAR + watchAR calls. For example, I'd expect initAR to be called on page load. And the response to initAR not to call watchAR right away.
Thoughts?
