### ISSUE TITLE
Need to check if location permission has been granted

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#64]
Right now, if the app doesn't have location, the video freezes (see issue  #56).  Need to somehow check if the app doesn't have location permission, and alert the user.  Hopefully, we can run without it (I don't know why it was freezing)

**Comment by blairmacintyre** [comment]
It is unclear if this is just an internal bug (e.g., the flow of the code is such that if location is not enabled, there is a hang wait for it) or if the app needs location.  I would assume the first (e.g., things should work if you don't have location enabled).

BUT, we may want to surface that somehow, in a warning?  I could imagine adding a line to the settings saying "app needs location permission for web geolocation API to work", for example.  HOWEVER, this is low priority, as long as the app doesn't hang when location isn't available.

**Comment by che1404** [comment]
@blairmacintyre on the iPad, if I remove the location permissions from the iOS settings, the AR apps keep working. So probably the location is not needed?

**Comment by blairmacintyre** [comment]
But, without location enabled in the app,  the location API in the webview doesn't work.
