### ISSUE TITLE
Ask for user permissions on the first launch in a nicer way

### ISSUE THREAD

**Issue by che1404** [mozilla-mobile/webxr-ios#65]
Location services access is compulsory in order to configure an ARSession aligned with the true North. Since this is the current default -hard coded- way to configure the session, we must instantiate the CLLocationManager on app launch. This causes the permissions popup to be shown the first time the user launches the app.

The idea is to change this behavior so that the first time the user launches the app, we first show a "permissions view controller". Within this view controller we need to show a short text explaining why we need that specific permission, and also let the user enable one at a time by tapping the respective button.

We are currently asking for the following permissions:
- CoreLocation
- Camera
- Camera roll
- Screen Recording (with/without mic support)

(We could grab some ideas from here: https://www.pinterest.es/enzokin/permissions/?lp=true)

**Comment by blairmacintyre** [comment]
This should also include this https://github.com/mozilla-mobile/webxr-ios/issues/49 (don't ask for camera roll till they try and save something).  

The screen recording doesn't ask till you try doing it, right?

**Comment by che1404** [comment]
> This should also include this #49 (don't ask for camera roll till they try and save something).

My initial idea was to ask for everything in the same view the first time the user launches the app, explaining why we are requesting those permissions. But we'll need to show it again, if for some reason he didn't give us permissions initially. Does it make sense?


> The screen recording doesn't ask till you try doing it, right?

Yes, that's how it works now

**Comment by blairmacintyre** [comment]
that makes sense.

**Comment by blairmacintyre** [comment]
done
