### ISSUE TITLE
when the URL bar is empty, tap or press doesn't bring up a "paste" option

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#67]
If there is nothing in the URL bar, there is no way to bring up the little "cut / copy / paste" menu.  

If I have a URL I want to paste, the obvious approach is to bring up the URL bar, click the "x" to clear it, then tap to get a menu containing "paste" ... but no menu appears.

**Comment by robomex** [comment]
Resolved.
