### ISSUE TITLE
need a way to reset ARKit

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#72]
Now that ARKit isn't restarted on each page, and continues running in the background, we need a direct way to restart.  

Problem is, if it's sleeping too long, or you just want a fresh start, there is no simple way to restart.

Ideas:
- if it's idle + backgrounded for more than a few minutes, say 5, the next watchAR restarts?
- reloading the same URL in a short time (a few seconds?) restarts instead of resumes?
- button or menu item to restart tracking?

**Comment by che1404** [comment]
I've implemented all these 3 techniques on **wip_initAR_watchAR_stopAR** branch. 
The button to restart tracking is just a button with an "R", but of course I'm open to icon suggestions. I usually use fontawesome icons, but maybe somebody has a better alternative.
Any feedback would be appreciated!

**Comment by che1404** [comment]
Blair:

> You could change your “R” button to pop up a dialog with options and explanations of what they would do?

**Comment by blairmacintyre** [comment]
works
