### ISSUE TITLE
Did you consider adopting some ideas of EjectaJS ?

### ISSUE THREAD

**Issue by PixelPartner** [mozilla-mobile/webxr-ios#76]
[Framework for fast native Graphics in webkit](https://github.com/phoboslab/Ejecta)
For example it renders all WebGL with native OpenGLES

**Comment by blairmacintyre** [comment]
No, we didn't.

Any application that downloads arbitrary content from the internet must use iOS wkWebView.  You can use alternative webviews only for apps that bundle all their code or download content from controlled, non-arbitrary places.

If we should ship our own webview, we would have used Gecko or Servo and extended it to support WebXR natively!

**Comment by PixelPartner** [comment]
May bad to not think about the `arbitrary content` rules.
