### ISSUE TITLE
Let demo app be launched with an URLScheme

### ISSUE THREAD

**Issue by PixelPartner** [mozilla-mobile/webxr-ios#80]
I imagine the App to be launched and load `contentURL` when a QR-Code or external link references `mozillaxr://contentURL`

**Comment by blairmacintyre** [comment]
We haven't broadly announced it, because we don't want to give the impression that this is a "proposal for anything", but we already support this:   try `wxrv://contentURL` ... loads as `https://contentURL`.

I have page in my Notes app with all my links. ;)
