### ISSUE TITLE
Debug information is only shown when the URL bar is visible

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#83]
Debug information should be shown when the URL bar is hidden, if it's been turned on

**Comment by robomex** [comment]
Resolved in [commit 81ddc85422d6e7b9ed105a013edd76c0a40c4f74](https://github.com/mozilla-mobile/webxr-ios/commit/81ddc85422d6e7b9ed105a013edd76c0a40c4f74).
