### ISSUE TITLE
Out-of-memory crashes

### ISSUE THREAD

**Issue by bertfreudenberg** [mozilla-mobile/webxr-ios#95]
I tried the "Simplest AR" teapot example on both an iPhone 6S and iPad Pro 9.7, worked on both for a couple seconds, but then crashed with an out-of-memory error.

iOS 11.4, app version 1.09

**Comment by blairmacintyre** [comment]
I've had this happen, but not repeatably.  I generally chock it up to "my phone was low enough on memory when I ran it and iOS couldn't shut down other apps fast enough to relieve memory pressure".  There could be a lot of optimizations done to the internals to allocate less memory per frame, we're pushing the garbage collector pretty hard.

Is this repeatable for you?

I've given hour-long talks with the app being projected while running AR the whole time, on an iPhone 6Plus, iPad Pro 9.7, and iPhoneX.  I've never had it crash during one of those.

**Comment by bertfreudenberg** [comment]
I will give it a more thorough look and report back.

**Comment by blairmacintyre** [comment]
I haven't seen a crash it quite a while.  closing this.

**Comment by mattdesl** [comment]
I tend to get this every time I try the teapot example, iOS 13.3.1, iPhone 7.

**Comment by blairmacintyre** [comment]
If you run again after the crash, does it crash again?  Curious because (at least for me), it would rarely crash multiple times in a row (my hypothesis being that it would just not be able to clear out memory fast enough and crash, but iOS would kill a few other things at the same time and it would work after).
